config/routes.rb
QuickSearch::Engine.routes.draw do

  root 'search#index'

  get 'xhr_search' => 'search#xhr_search', :defaults => { :format => 'html' }
  get 'log_event' => 'logging#log_event'
  get 'log_search' => 'logging#log_search'
  get 'typeahead' => 'typeahead#typeahead'

  get 'searcher/:searcher_name' => 'search#single_searcher'
  get 'searcher/:searcher_name/xhr_search' => 'search#xhr_search', :defaults => { :format => 'html' }
  get 'searcher/:searcher_name/log_event' => 'search#log_event'
  get 'searcher/:searcher_name/log_search' => 'search#log_search'

  get 'opensearch' => 'opensearch#opensearch', :defaults => { :format => 'xml' }

  get 'about' => 'pages#about'
  get 'realtime' => 'pages#realtime'
  get 'data_general_statistics' => 'appstats#data_general_statistics'
  get 'data_general_table' => 'appstats#data_general_table' 
  get 'data_module_clicks' => 'appstats#data_module_clicks'
  get 'data_result_clicks' => 'appstats#data_result_clicks'
  get 'data_module_details' => 'appstats#data_module_details'
  get 'data_top_searches' => 'appstats#data_top_searches'
  get 'data_spelling_suggestions' => 'appstats#data_spelling_suggestions'
  get 'data_spelling_details' => 'appstats#data_spelling_details'
  get 'data_best_bets' => 'appstats#data_best_bets'
  get 'data_best_bets_details' => 'appstats#data_best_bets_details'
  get 'data_sessions_overview' => 'appstats#data_sessions_overview'
  get 'data_sessions_location' => 'appstats#data_sessions_location'
  get 'data_sessions_device' => 'appstats#data_sessions_device'

  match 'appstats', to: 'appstats#index', via: [:get, :post]
  match 'appstats/clicks_overview', to: 'appstats#clicks_overview', as: 'clicks_overview', via: [:get, :post]
  match 'appstats/top_searches', to: 'appstats#top_searches', as: 'top_searches', via: [:get, :post]
  match 'appstats/top_spot', to: 'appstats#top_spot', as: 'top_spot', via: [:get, :post]
  match 'appstats/sessions_overview', to: 'appstats#sessions_overview', as: 'sessions_overview', via: [:get, :post]
  match 'appstats/sessions_details', to: 'appstats#sessions_details', as: 'sessions_details', via: [:get, :post]
  get 'appstats/realtime' => 'appstats#realtime'
  get 'appstats/data_general_statistics', :defaults => { :format => 'json' }
  get 'appstats/data_general_table', :defaults => { :format => 'json' }
  get 'appstats/data_module_clicks', :defaults => { :format => 'json' }
  get 'appstats/data_result_clicks', :defaults => { :format => 'json' }
  get 'appstats/data_module_details', :defaults => { :format => 'json' }
  get 'appstats/data_top_searches', :defaults => { :format => 'json' }
  get 'appstats/data_spelling_suggestions', :defaults => { :format => 'json' }
  get 'appstats/data_spelling_details', :defaults => { :format => 'json' }
  get 'appstats/data_best_bets', :defaults => { :format => 'json' }
  get 'appstats/data_best_bets_details', :defaults => { :format => 'json' }
  get 'appstats/data_sessions_overview', :defaults => { :format => 'json' }
  get 'appstats/data_sessions_location', :defaults => { :format => 'json' }
  get 'appstats/data_sessions_device', :defaults => { :format => 'json' }

end

app/controllers/concerns/quick_search/auth.rb
require "digest/md5"

module QuickSearch::Auth
  extend ActiveSupport::Concern

  SALT01 = SecureRandom.hex(512)
  SALT02 = SecureRandom.hex(512)
  REALM = "Please enter the username and password to access this page"
  USERS = {"#{QuickSearch::Engine::APP_CONFIG['user']}" => Digest::MD5.hexdigest(["#{QuickSearch::Engine::APP_CONFIG['user']}",REALM,"#{QuickSearch::Engine::APP_CONFIG['password']}"].join(":"))}
  SALTY = SALT01 + Digest::MD5.hexdigest(["#{QuickSearch::Engine::APP_CONFIG['user']}",REALM,"#{QuickSearch::Engine::APP_CONFIG['password']}"].join(":")) + SALT02

  def auth
    authenticate_or_request_with_http_digest(REALM) do |username|
      unless SALT01.blank? or SALT02.blank? or USERS[username].blank?
        if SALT01 + USERS[username] + SALT02 == SALTY
          USERS[username]
        end
      end
    end
  end

end

app/controllers/concerns/quick_search/doi_trap.rb
module QuickSearch::DoiTrap
  extend ActiveSupport::Concern

  include QuickSearch::EncodeUtf8

  private

  def doi_trap
    unless params_q_scrubbed.nil?
      if is_a_doi?(doi_query)
        Event.create(category: 'doi-trap', query: doi_query, action: 'click')
        redirect_to doi_loaded_link
        # Alternately insert a loaded link into the results interface
        # @doi_loaded_link = loaded_link
        # @doi_callout = "Searching for a DOI? Try this: "
      end
    end
  end

  def is_a_doi?(query)
    if doi_regex.match(query)
      true
    else
      false
    end
  end

  def doi_regex
    /^(?:(?:doi:?\s*|(?:http:\/\/)?(?:dx\.)?(?:doi\.org)?\/))?(10(?:\.\d+){1,2}\/\S+)$/i
  end

  def doi_loaded_link
     QuickSearch::Engine::APP_CONFIG['doi_loaded_link'] + CGI.escape(doi_regex.match(doi_query)[1])
  end

  def doi_query
    query = params_q_scrubbed
    query.strip!
    query.squish!
    query
  end

end

app/controllers/concerns/quick_search/encode_utf8.rb
module QuickSearch::EncodeUtf8
  extend ActiveSupport::Concern

  private

  def params_q_scrubbed
    unless params[:q].nil?
      params[:q].scrub
    end
  end

end

app/controllers/concerns/quick_search/on_campus.rb
module QuickSearch::OnCampus
  extend ActiveSupport::Concern

  private

  # Search for "Nucleation and growth mechanism of ferroelectric domain wall motion"
  # To test this. Result should not show up in Summon results off campus.

  ### WHY THIS IS HERE ###
  # There is a subset of Summon results that cannot be shown unless a person is
  # on campus or authenticated. So that we can show all results to people
  # searching QuickSearch from on campus we're checking IP addresses. If the IP is a
  # known campus IP we set the s.role=authenticated parameter in the Summon API request.

  def ip
    request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip
  end

  def on_campus?(ip)
    ip = remote_ip(ip)
    ip_range_check(ip)
  end

  # To spoof ON and OFF campus for development
  def remote_ip(ip)
    if ip == '127.0.0.1'
      '204.84.244.1' #On Campus
      #'127.0.0.1'  #Off Campus
    else
      ip
    end
  end

  def ip_range_check(ip)
    QuickSearch::Engine::APP_CONFIG['on_campus'].each do |on_campus_ip_regex|
      if on_campus_ip_regex === ip
        return true
      end
    end

    return false
  end
end

app/controllers/concerns/quick_search/query_filter.rb
module QuickSearch::QueryFilter
  extend ActiveSupport::Concern

  include ActionView::Helpers::TextHelper

  private

  def filter_query(query)
    if query.match(/ -$/)
      query = query.sub(/ -$/,"")
    end
    query.gsub!('*', ' ')
    query.gsub!('!', ' ')
    query.gsub!('-', ' ') # Solr returns an error if multiple dashes appear at start of query string
    query.gsub!('\\', '')
    # query.gsub!('"', '')
    query.strip!
    query.squish!
    query.downcase! # FIXME: Do we really want to downcase everything?
    query = truncate(query, length: 100, separator: ' ', omission: '', escape: false)

    query
  end

end

app/controllers/concerns/quick_search/query_parser.rb
module QuickSearch::QueryParser
  extend ActiveSupport::Concern

  private

  def extracted_query(unfiltered_query)
    @unfiltered_query = unfiltered_query
    if extracted_query_and_scope
      query = extracted_query_and_scope[:query]
    else
      query = unfiltered_query
    end
    query
  end

  def extracted_scope(unfiltered_query)
    @unfiltered_query = unfiltered_query
    if extracted_query_and_scope
      scope = extracted_query_and_scope[:value]
    else
      scope = ''
    end
  end

  def extracted_query_and_scope
    if regex_matches = prefix_scope_multi_regex.match(@unfiltered_query)
      regex_matches
    elsif regex_matches = suffix_scope_multi_regex.match(@unfiltered_query)
      regex_matches
    elsif regex_matches = prefix_scope_regex.match(@unfiltered_query)
      regex_matches
    elsif regex_matches = suffix_scope_regex.match(@unfiltered_query)
      regex_matches
    end
    regex_matches
  end

  def prefix_scope_regex
    /^(?<option>scope):(?<value>\S+)\s?(?<query>.*)$/
  end

  def prefix_scope_multi_regex
    /^(?<option>scope):\((?<value>.*?)\)\s?(?<query>.*)$/
  end

  def suffix_scope_regex
    /(?<query>.*)\s(?<option>scope):(?<value>\S+)/
  end

  def suffix_scope_multi_regex
    /^(?<query>.*)\s(?<option>scope):\((?<value>.*)\)$/
  end

end

app/controllers/concerns/quick_search/searcher_concern.rb
module QuickSearch::SearcherConcern
  extend ActiveSupport::Concern

  include QuickSearch::OnCampus
  include QuickSearch::QueryParser
  include QuickSearch::EncodeUtf8
  include QuickSearch::SearcherConfig
  require 'benchmark_logger'
  require_dependency 'searcher_error'

  private

  def search_all_in_threads(primary_searcher = 'defaults')
    benchmark "%s server ALL" % CGI.escape(query.to_str) do
      search_threads = []
      @found_types = [] # add the types that are found to a navigation bar

      if primary_searcher == 'defaults'
        searchers = QuickSearch::Engine::APP_CONFIG['searchers']
      else
        searcher_config = searcher_config(primary_searcher)
        if searcher_config and searcher_config.has_key? 'with_paging'
          searchers = searcher_config['with_paging']['searchers']
        else
          searchers = [primary_searcher]
        end
      end

      # Constantize all searchers before creating searcher threads
      # Excluding this line causes threads to hang indefinitely as of Rails 5
      QuickSearch::Engine::APP_CONFIG['searchers'].each do |searcher_name|
        "QuickSearch::#{searcher_name.camelize}Searcher".constantize
      end

      searchers.shuffle.each do |search_method|
        search_threads << Thread.new(search_method) do |sm|
          benchmark "%s server #{sm}" % CGI.escape(query.to_str) do
            begin
              klass = "QuickSearch::#{sm.camelize}Searcher".constantize

              http_client = HTTPClient.new
              update_searcher_timeout(http_client, sm)
              # FIXME: Probably want to set paging and offset somewhere else.
              # searcher = klass.new(http_client, params_q_scrubbed, QuickSearch::Engine::APP_CONFIG['per_page'], 0, 1, on_campus?(request.remote_ip))
              if sm == primary_searcher
                if searcher_config.has_key? 'with_paging'
                  per_page = searcher_config['with_paging']['per_page']
                else
                  per_page = 10
                end
                searcher = klass.new(http_client, query, per_page, offset(page, per_page), page, on_campus?(ip), scope)
              else
                searcher = klass.new(http_client, query, QuickSearch::Engine::APP_CONFIG['per_page'], 0, 1, on_campus?(ip), scope)
              end
              searcher.search
              unless searcher.is_a? StandardError or searcher.results.blank?
                @found_types.push(sm)
              end
              instance_variable_set "@#{sm}", searcher
            rescue StandardError => e
              # logger.info e

              # Wrap e in a SearcherError, so that the searcher object is
              # available for retrieval.
              searcher_error = QuickSearch::SearcherError.new(e, searcher)
              logger.info "FAILED SEARCH: #{sm} | #{params_q_scrubbed}"
              instance_variable_set :"@#{sm.to_s}", searcher_error
            end
          end
        end
      end
      search_threads.each {|t| t.join}
    end
  end


  def page
    if page_in_params?
      page = params[:page].to_i
    else
      page = 1
    end
    page
  end

  def offset(page, per_page)
    (page * per_page) - per_page
  end

  def query
    extracted_query(params_q_scrubbed)
  end

  def scope
    extracted_scope(params_q_scrubbed)
  end

  def update_searcher_timeout(client, search_method, xhr=false)
    timeout_type = xhr ? 'xhr_http_timeout' : 'http_timeout'
    timeout = QuickSearch::Engine::APP_CONFIG[timeout_type]

    if QuickSearch::Engine::APP_CONFIG.has_key? search_method and QuickSearch::Engine::APP_CONFIG[search_method].has_key? timeout_type
        timeout = QuickSearch::Engine::APP_CONFIG[search_method][timeout_type]
    end

    client.receive_timeout = timeout
    client.send_timeout = timeout
    client.connect_timeout = timeout
  end

end

app/controllers/concerns/quick_search/searcher_config.rb
module QuickSearch::SearcherConfig
  extend ActiveSupport::Concern

  private

  def searcher_config(searcher)
    # Best Bets searcher is available in QuickSearch core, use app_config
    if searcher == 'best_bets'
      QuickSearch::Engine::APP_CONFIG['best_bets']
    else
      begin
        "QuickSearch::Engine::#{searcher.upcase}_CONFIG".constantize
      rescue NameError
        nil
      end
    end
  end

end

app/controllers/quick_search/application_controller.rb
module QuickSearch
  class ApplicationController < ::ApplicationController
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
  end
end

app/controllers/quick_search/opensearch_controller.rb
module QuickSearch
  class OpensearchController < ApplicationController

    def opensearch
      response.headers['Content-Type'] = 'application/opensearchdescription+xml; charset=utf-8'
    end

  end
end

app/controllers/quick_search/pages_controller.rb
module QuickSearch
  class PagesController < ApplicationController

    include Auth

    before_action :auth, only: [:realtime]

    def home
    end

    def about
    end

    def realtime
    end

  end
end

app/controllers/quick_search/typeahead_controller.rb
module QuickSearch
  class TypeaheadController < ApplicationController
    protect_from_forgery except: :typeahead

    # This method should return a list of search suggestions for a given searcher
    # It should return errors if there is no param called 'searcher', if the searcher does not exist
    # or if the searcher doesn't implement the 'typeahead' method
    # Otherwise, it should return the result of calling the 'typeahead' method as JSON

    def typeahead
      # :searcher param expected to be name of a searcher with underscores, ie: ematrix_journal
      searcher = params[:searcher]
      query = params[:q] or ''
      total = params[:total] or 3

      if searcher.blank?
        logger.error "Typeahead request: no searcher param provided"
        head :bad_request
        return nil
      end

      searcher_string = "QuickSearch::#{searcher.camelize}Searcher"

      begin 
        klass = searcher_string.constantize
      rescue NameError
        logger.error "Typeahead request: searcher #{searcher} does not exist"
        head :bad_request
        return nil
      end

      if klass.method_defined? :typeahead
        typeahead_result = klass.new(HTTPClient.new, query, total).typeahead

        if params.has_key? 'callback'
          render json: typeahead_result, callback: params['callback']
        else
          render json: typeahead_result
        end
      else
        logger.error "Typeahead request: searcher #{searcher} has no typeahead method"
        head :bad_request
        return nil
      end
    end

  end
end

app/helpers/quick_search/application_helper.rb
module QuickSearch::ApplicationHelper
  include QuickSearch::EncodeUtf8

  def application_name
    if action_name == "website"
      I18n.t "website_search.title_name"
    else
      I18n.t "defaults_search.title_name"
    end
  end

  def organization_name
    I18n.t 'organization_name'
  end

  def sanitized_query
    params_q_scrubbed.nil? || params_q_scrubbed == "" ? "" : sanitize(params_q_scrubbed)
  end

  def display_query
    params_q_scrubbed.nil? || params_q_scrubbed == "" ? "" : truncate(params_q_scrubbed, length: 40, separator: ' ')
  end

  def log_query
    params_q_scrubbed.nil? || params_q_scrubbed == "" ? "" : truncate(sanitize(params_q_scrubbed), length: 100, separator: ' ')
  end

  def title(page_title = nil)
    query = params_q_scrubbed.nil? || params_q_scrubbed == "" ? "" : truncate(params_q_scrubbed, length: 40, separator: ' ', escape: false)
    page_title ||= ''
    page_title << "#{query} |" unless query.blank?
    page_title << " #{application_name} |" unless application_name.blank?
    page_title << " #{organization_name}" unless organization_name.blank?

    content_for :title, page_title
  end

  # FIXME this should use en definitions
  def pages(page)
    format_pages ||= ''
    if page.count('-') > 0
      format_pages << "pp.&nbsp;"
    else
      format_pages << "p.&nbsp;"
    end
    format_pages << page
  end

  def render_module(searcher, service_name, partial_name = '/quick_search/search/module', per_page = 3)
    render partial: partial_name , locals: { module_display_name: t("#{service_name}_search.display_name"), searcher: searcher, search: '', service_name: service_name, per_page: per_page }
  end

  def get_best_bets_data(best_bets_searcher)
    best_bets = {}
    best_bets[:id] = best_bets_searcher.results.first.id
    best_bets[:title] = best_bets_searcher.results.first.title
    best_bets[:link] = best_bets_searcher.results.first.link
    best_bets[:description] = best_bets_searcher.results.first.description
    best_bets[:best_bets_type] = best_bets_searcher.results.first.best_bets_type

    best_bets
  end

 def body_class
    [controller_name, action_name].join('-')
  end

end

app/helpers/quick_search/appstats_helper.rb
module QuickSearch::AppstatsHelper
end

app/helpers/quick_search/opensearch_helper.rb
module QuickSearch::OpensearchHelper
end

app/helpers/quick_search/pages_helper.rb
module QuickSearch::PagesHelper
end

app/helpers/quick_search/search_helper.rb
module QuickSearch::SearchHelper
end

app/views/layouts/quick_search/_best_bets.html.erb
<% unless best_bets.blank? %>
    <% if best_bets[:link].is_a?(String) %>
        <div id="best-bets" class="row quicksearch-ga-serve-tracking quicksearch-ga-click-tracking">
            <div class="small-12 columns best_bets module">
                <h3 class='title'>
                    <%= link_to (best_bets[:link]),
                        :data => { :quicksearch_ga_action => best_bets[:id], 
                          :quicksearch_ga_category => best_bets[:best_bets_type] } do  %>
                            <i class='fa fa-angle-double-right'></i> 
                            <%= best_bets[:title] %>
                    <% end %>
                     <span class='highlight'>Best&nbsp;Bet</span>
                </h3>
             
				<p>
					<% if best_bets[:description].length > 200 %>
				    <%= truncate(best_bets[:description], length: 200) %>
				    <%= link_to 'Read more', '', class: "read-more" %>
				    <script>
				      $('.read-more').on('click', function(e) {
				        e.preventDefault()
				        $(this).parent().html('<%= escape_javascript best_bets[:description] %>')
				      })
				    </script>
				  <% else %>
				    <%= best_bets[:description] %>
				  <% end %>
			  </p>
            </div>
        </div>
    <% end %>
<% end %>

app/views/layouts/quick_search/_common_searches.html.erb
<div class="row">
    <div class="small-12 medium-7 columns">
        <h2><%= @module_callout %></h2>
    </div>
    <% unless @common_searches.empty? %>
        <div id="common-searches" class="small-12 medium-5 columns common-searches">
            <h4><%= t('call_to_try_searches') %>:</h4>
            <ul>
                <% @common_searches.each do | search | %>
                    <li><%= link_to search, :q => search  %></li>
                <% end %>
            </ul>
        </div>
      <% end %>
</div>

app/views/layouts/quick_search/_found_types.html.erb
<ul class="inline-list">
<% for searcher in QuickSearch::Engine::APP_CONFIG['found_types'] %>
        <% if @found_types.include? searcher  %>
            <li>
                <a href="#<%= searcher.dasherize %>" data-quicksearch-ga-action="<%= searcher.dasherize %>">
                <%= t("#{searcher}_search.display_name") %>
                </a>
            </li>
        <% else %>
            <li class="<%= searcher.dasherize %>"><span class="no-results-label"><%= t("#{searcher}_search.display_name") %></span></li>
        <% end %>
<% end %>
</ul>

app/views/layouts/quick_search/_google_analytics.html.erb
<% if Rails.env == 'production' or Rails.env == 'staging' %>
<script>
// Universal analytics
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");

ga("create", "<%= QuickSearch::Engine::APP_CONFIG['google_analytics_tracking_id'] %>", "auto");
ga("send", "pageview");

</script>
<% end %>

app/views/layouts/quick_search/_more_options.html.erb
<% if @query %>
    <h4>More search options for <span class="query">"<%= display_query %>"</span></h4>
<% else %>
    <h4>A few more places to try:</h4>
<% end %>
<ul>
    <% @search_services_for_display.each do |link| %>
        <li><%= link_to link['name'], link['link'] %></li>
    <% end %>
</ul>

app/views/layouts/quick_search/_page_title.html.erb
<div class="row">
    <div class="small-12 medium-6 large-9 columns">
        <h1>Search <%= page_title %></h1>
    </div>
    <div class="medium-6 large-3 columns show-for-medium-up">
        <p><%= link_to 'About this search tool', about_path, class: 'about' %></p>
    </div>
</div>

app/views/layouts/quick_search/_related_topics.html.erb
<% unless related_topics.blank? %>
    <h4>Related searches</h4>
    <ul>
    <% related_topics.each do |topic| %>
        <li><%= link_to topic, root_path(q: topic) %></li>
    <% end %>
    </ul>
<% end %>

app/views/layouts/quick_search/_search_form.html.erb
<div class="row main-search-form">
    <div class="small-12 columns">
    <%= form_for("search", method: :get, html: {id: 'main-search-form'}) do |f| %>
        <div class="row collapse">
            <div class="small-10 columns">
                <% if @query  %>
                    <input type="search" name="q" id="params-q" class="search-query" value="<%= @query %>" />
                <% else %>
                    <input type="search" name="q" id="params-q" class="search-query" placeholder="<%= @search_form_placeholder %>" />
                <% end %>
            </div>
            <div class="small-2 columns">
                <button type="submit" class="button prefix show-for-small"><i class="fa fa-search"></i></button>
                <button type="submit" class="button prefix show-for-medium-up">Search</button>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/layouts/quick_search/_spelling_suggestion.html.erb
<% unless spelling_suggestion.blank? %>
    <% unless @query.size > 100 %>
    <div id='spelling-suggestion' class="row quicksearch-ga-serve-tracking quicksearch-ga-click-tracking">
      <div class="small-12 large-8 columns spelling-suggestion module">
        <h3 class="title">
          Did you mean <%= link_to spelling_suggestion, "?q=#{spelling_suggestion}",
            :data => { :quicksearch_ga_action => spelling_suggestion,
            :quicksearch_ga_label => @query }  %>?
        </h2>
      </div>
    </div>
    <% end %>
<% end %>

app/views/layouts/quick_search/_topic_snippet.html.erb
<% unless topic_snippet.blank? %>
    <h2><a href="<%=  topic_snippet['source_link'] %>"><%= topic_snippet['title'] %></a></h2>
    <p><%= topic_snippet['snippet'] %></p>
    <p>Source: <a href="<%=  topic_snippet['source_link'] %>"><%= topic_snippet['source_name'] %></a></p>
<% end %>

app/views/layouts/quick_search/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <title><%= content_for(:title) %></title>
    <meta content="ie=edge, chrome=1" http-equiv="x-ua-compatible" />
    <link rel="search" type="application/opensearchdescription+xml" href="<%= opensearch_path %>" title="<%= t('opensearch_description') %>" />
    <!-- css -->
    <%= stylesheet_link_tag 'application' %>

    <!-- js -->
    <%= javascript_include_tag 'application' %>
    <%= render '/layouts/quick_search/head' %>
    <%= render '/layouts/quick_search/google_analytics' %>

    <!-- datepicker (temp) -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body class="<%= body_class %>" data-quicksearch-ga-query="<%= strip_tags(@log_query) %>">
<div class="off-canvas-wrap">
<div class="inner-wrap">
<%= render '/layouts/quick_search/header' %>
<div id="content" role="document" class="page">
    <main id="main-content" role="main" class="row l-main">
        <div class="medium-12 main columns">
            <div class="skip-link">
                <a href="#main-content"></a>
            </div>
            <!-- CONTENT: enter content below this line -->
            <div id="quicksearch">
            <%= yield %>
            </div>
        </div>
    </main>
</div>
<%= render '/layouts/quick_search/footer' %>
</div>
</div>
<script type="text/javascript">$(function() { $('body').hide().show(); });
window.I18n = <%= I18n.backend.send(:translations).to_json.html_safe %>
</script>
</body>
</html>